In [5]:
import pandas as pd
from pathlib import Path

RAW_DIR = Path("../data/raw")

players = pd.read_csv(RAW_DIR / "players.csv")
valuations = pd.read_csv(RAW_DIR / "player_valuations.csv")
appearances = pd.read_csv(RAW_DIR / "appearances.csv")
clubs = pd.read_csv(RAW_DIR / "clubs.csv")
competitions = pd.read_csv(RAW_DIR / "competitions.csv")

print("Players:", players.shape)
print("Valuations:", valuations.shape)
print("Appearances:", appearances.shape)
print("Clubs:", clubs.shape)
print("Competitions:", competitions.shape)

Players: (47702, 26)
Valuations: (616377, 6)
Appearances: (1862208, 13)
Clubs: (796, 17)
Competitions: (67, 11)

In [2]:
print("\nPLAYERS:\n",players.columns.tolist())
print("\nVALUATIONS:\n",players.columns.tolist())
print("\nAPPEARANCES:\n",players.columns.tolist())

PLAYERS:
 ['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

VALUATIONS:
 ['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

APPEARANCES:
 ['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

In [10]:
appearances.head(1)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90

In [12]:
player_stats=appearances.groupby("player_id").agg({
    "minutes_played":"sum",
    "goals":"sum",
    "assists":"sum"
}).reset_index()

player_stats.head(10)

   player_id  minutes_played  goals  assists
0         10            8808     48       25
1         26           13508      0        0
2         65            8788     38       13
3         77             307      0        0
4         80            1080      0        0
5        109            3584      1        2
6        123             427      0        1
7        132            3987      9        4
8        215            6038     26        8
9        258            1075      0        2

In [13]:
valuations_sorted = valuations.sort_values("date", ascending=False)

latest_valuations = valuations_sorted.drop_duplicates(subset=["player_id"])

latest_valuations = latest_valuations[["player_id", "market_value_in_eur"]]

latest_valuations.head()

        player_id  market_value_in_eur
616376    1519157               100000
616284     668731               700000
616290     701224              2200000
616289     688019               800000
616288     685657              2000000

In [14]:
player_info = players[[
    "player_id",
    "name",
    "date_of_birth",
    "position",
    "current_club_id"
]]

player_info.head()

,player_id,name,date_of_birth,position,current_club_id
0,10,Miroslav Klose,1978-06-09 00:00:00,Attack,398
1,26,Roman Weidenfeller,1980-08-06 00:00:00,Goalkeeper,16
2,65,Dimitar Berbatov,1981-01-30 00:00:00,Attack,1091
3,77,Lúcio,1978-05-08 00:00:00,Defender,506
4,80,Tom Starke,1981-03-18 00:00:00,Goalkeeper,27

In [17]:
final_df=player_info.merge(player_stats,on='player_id',how='inner')
final_df=final_df.merge(latest_valuations,on='player_id',how='inner')
final_df.head()

,player_id,name,date_of_birth,position,current_club_id,minutes_played,goals,assists,market_value_in_eur
0,10,Miroslav Klose,1978-06-09 00:00:00,Attack,398,8808,48,25,1000000
1,26,Roman Weidenfeller,1980-08-06 00:00:00,Goalkeeper,16,13508,0,0,750000
2,65,Dimitar Berbatov,1981-01-30 00:00:00,Attack,1091,8788,38,13,1000000
3,77,Lúcio,1978-05-08 00:00:00,Defender,506,307,0,0,200000
4,80,Tom Starke,1981-03-18 00:00:00,Goalkeeper,27,1080,0,0,100000

In [18]:
final_df.shape

(27641, 9)